[package]
name = "miniraft"
version = "0.1.0"
authors = ["scturtle <scturtle@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
log = "0.4"
env_logger = "0.7"
rand = "0.7"
async-std = { version = "1.5", features = ["unstable"] }
futures = "0.3"
miniserde = "0.1"
